a=int(input("enter first number :"))
b=int(input("enter second number :"))
print ("before swapping a=",a)
print ("before swapping b=",b)
a=a+b
b=a-b
a=a-b
print ("after swapping a=",a)
print ("after swapping b=",b)